name: Rest Assured

on: [push]

jobs:
  api-testing:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Set up JDK
        uses: actions/setup-java@v5.5.0
        with:
          distribution: 'temurin'
          java-version-file: .java-version
      - name: Run gradlew
        run: ./gradlew test
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: report.html
          path: build/reports/tests/test/index.html